name: EaglercraftXServer
version: 1.0.1
main: net.lax1dude.eaglercraft.backend.server.bukkit.PlatformPluginBukkit
description: Official EaglercraftX plugin for Spigot and Paper servers
author: lax1dude
softdepend:
- SkinsRestorer