name: EaglercraftXPlan
version: 1.0.0
main: net.lax1dude.eaglercraft.backend.plan.bukkit.PlatformPluginBukkit
description: Official Plan player analytics integration plugin for EaglercraftXServer
authors:
  - lax1dude
  - ayunami2000
depend:
  - EaglercraftXServer
  - Plan